framework:
    messenger:
        
        default_bus: event.bus
        buses:
            event.bus:
                default_middleware:
                    enabled: true
                    # set "allow_no_handlers" to true (default is false) to allow having
                    # no handler configured for this bus without throwing an exception
                    allow_no_handlers: false
                    # set "allow_no_senders" to false (default is true) to throw an exception
                    # if no sender is configured for this bus
                    allow_no_senders: true
                middleware:
                    - validation
        
        transports:
            async_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 5
                    delay: 2000
                    multiplier: 3
                    max_delay: 0
        
        routing:
            App\Service\Conversion\Event\ConvertTypeToTypeEvent: async_transport
            App\Service\Conversion\Event\SendConvertedFilesEvent: async_transport
            
            App\Service\Conversion\Event\CombineTypesToTypeEvent: async_transport
            App\Service\Conversion\Event\SendCombinedFileEvent: async_transport

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
