framework:
    messenger:
        default_bus: event.bus
        buses:
            async.bus:
                default_middleware:
                    allow_no_handlers: true
            event.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: false
                    allow_no_senders: true
                middleware:
                    - validation
        
        transports:
            process_files:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'process_files'
                    queues:
                        process_files_queue: ~
                retry_strategy:
                    max_retries: 5
                    delay: 2000
                    multiplier: 3
                    max_delay: 0
            
            save_processed_files:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'save_processed_files'
                    queues:
                        save_processed_files_queue: ~

        routing:
            App\Service\Process\Event\External\ProcessFilesEvent: process_files
            
            App\Service\Process\Event\External\SaveProcessedFilesEvent: save_processed_files

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
