version: '3.9'

services:

    nginx:
        build:
            context: ./nginx
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-nginx
        working_dir: /var/www/html
        environment:
            - VIRTUAL_HOST=${DOMAIN}
        depends_on:
            - app
        volumes:
            ###> NGINX VOLUMES
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-enabled/app.conf:/etc/nginx/sites-enabled/${CONTAINER_NAME:-unnamed}.conf
            - ./nginx/logs/access.log:/var/log/nginx/access.log
            - ./nginx/logs/error.log:/var/log/nginx/error.log
            ###> TIMEZONE VOLUMES
            - /etc/localtime:/etc/localtime:ro
            ###> PROJECT VOLUME ###
            - ${PROJECT_PATH:-../}:/var/www/html
        networks:
            - reverse-proxy
            - backend

    app:
        build:
            context: ./app
            args:
                PHP: ${PHP_VERSION}
                NAME: ${CONTAINER_NAME:-unnamed}
        user: 1000:1000
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-app
        working_dir: /var/www/html
        stdin_open: true
        tty: true
        environment:
            ### PHP ENV ###
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
            - VIRTUAL_PROTO=fastcgi
            ###> BASH COLORS ###
            - TERM=xterm-256color
            - PS1=${PS1}
            - PHP_IDE_CONFIG=${XDEBUG_SERVER_NAME}
        volumes:
            ###> BASH VOLUMES ###
            - ./bash/.bash_aliases:/home/${USER}/.bash_aliases
            - ./bash/.bash_history:/${USER}/.bash_history
            - ./bash/.bashrc:/home/${USER}/.bashrc
            ###> COMPOSER VOLUMES ###
            - ${COMPOSER_CONFIG_PATH:-./composer/.config}:/home/${USER}/.composer
            - ${COMPOSER_CACHE_PATH:-./composer/.cache}:/home/${USER}/.cache/composer
            ###> TIMEZONE VOLUMES
            - /etc/localtime:/etc/localtime:ro
            ###> PHP INI VOLUME
            - ./app/php.ini:/usr/local/etc/php/conf.d/custom.php.ini
            ###> PROJECT VOLUME ###
            - ${PROJECT_PATH:-../}:/var/www/html
            - ./app/supervisord.conf:/etc/supervisord.conf
            ###> XDEBUG ###
            - ./app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        extra_hosts:
            - api.pdf.local:${DOCKER_IP}
        networks:
            - backend
            - rabbitmq

networks:
    backend:
        driver: bridge
        name: ${CONTAINER_NAME:-unnamed}_backend_network
    
    rabbitmq:
        name: ${RABBITMQ_NETWORK_NAME:-pdf_api_rabbitmq}
        external: true
        
    reverse-proxy:
        name: ${PROXY_NETWORK_NAME:-docker_engine_reverse_proxy}
        external: true