kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-config
data:
  supervisor.conf: |
    [supervisord]
    nodaemon=true

    [program:unoserver]
    command=unoserver

    [program:php-fpm]
    command=php-fpm