kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-config
data:
  supervisor.conf: |
    [supervisord]
    nodaemon=true
    loglevel=info

    [program:unoserver]
    command=unoserver
    stdout_events_enabled=true
    stderr_events_enabled=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    redirect_stderr=true

    [program:php-fpm]
    command=php-fpm
    stdout_events_enabled=true
    stderr_events_enabled=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    redirect_stderr=true

    [program:messenger-consume]
      directory=/var/www/html
      command=php bin/console messenger:consume async_transport --time-limit=3600
      startsecs=0
      autostart=true
      autorestart=true
      startretries=10
      stdout_events_enabled=true
      stderr_events_enabled=true
      stdout_logfile=/dev/stdout
      stdout_logfile_maxbytes=0
      redirect_stderr=true

  php.ini: |
    date.timezone = Europe/Moscow
    intl.default_locale = ru
    upload_max_filesize = 10M
    post_max_size = 100M
    opcache.enable_cli = 1