parameters:

framework:
  http_client:
    scoped_clients:
      conversion.client:
        base_uri: '%env(string:CONVERSION_BASE_URL)%'
        retry_failed:
          enabled: true
          max_retries: 3
          delay: 1000
          multiplier: 3
          max_delay: 5000
          jitter: 0.3

services:
  _defaults:
    autowire: true
    autoconfigure: true
  